# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Jianwei Zhang
tagline:          'Jianwei ZHang'
description:      'Welcome, this is a place for my ideas and thinking in coding.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Jianwei Zhang'
  url:            https://twitter.com/

paginate:         5
#
## Custom vars
#version:          2.1.0

github:
  repo:           https://github.com/zjwbupt
